// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  // The CLI (migrate/db) uses this connection. Migrations require the direct,
  // session-mode connection (DIRECT_URL, port 5432). Using the transaction
  // pooler (DATABASE_URL, port 6543) causes "prepared statement already
  // exists" (42P05) because pooled backends are recycled between clients.
  datasource: {
    url: env('DIRECT_URL'),
  },
});
